import { spawn } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { prepareFrontendDev } from "./clean-next-lock.mjs";
import { ensurePortFree, findAvailablePort } from "./clean-backend-port.mjs";

const FRONTEND_PORT = 3000;
const preferredBackendPort = Number(process.env.BACKEND_PORT || process.env.PORT) || 8000;
const envLocalPath = join(process.cwd(), ".env.local");

prepareFrontendDev();
ensurePortFree(String(preferredBackendPort));

const backendPort = await findAvailablePort(preferredBackendPort);
const apiUrl = `http://localhost:${backendPort}`;

writeFileSync(
  envLocalPath,
  `# Auto-generated by npm run dev:all — updated each start\nNEXT_PUBLIC_API_URL=${apiUrl}\n`,
  "utf8",
);

if (backendPort !== preferredBackendPort) {
  console.log(
    `[dev:all] Backend port ${preferredBackendPort} is in use. API: ${apiUrl} | Frontend: http://localhost:${FRONTEND_PORT}`,
  );
} else {
  console.log(
    `[dev:all] Backend API: ${apiUrl} | Frontend: http://localhost:${FRONTEND_PORT}`,
  );
}
console.log("[dev:all] Keep this terminal open while developing.");

const children = [];
let shuttingDown = false;

function runNpmScript(script, env) {
  const child = spawn("npm", ["run", script], {
    cwd: process.cwd(),
    env,
    stdio: "inherit",
    shell: true,
  });
  child.on("exit", (code, signal) => {
    if (shuttingDown) {
      return;
    }
    shuttingDown = true;
    console.error(
      `[dev:all] ${script} exited (${signal ?? code ?? "unknown"}). Stopping other processes.`,
    );
    for (const other of children) {
      if (other !== child && !other.killed) {
        other.kill();
      }
    }
    process.exit(code ?? (signal ? 1 : 0));
  });
  children.push(child);
  return child;
}

const frontendEnv = { ...process.env, NEXT_PUBLIC_API_URL: apiUrl };
delete frontendEnv.PORT;
delete frontendEnv.BACKEND_PORT;

const backendEnv = { ...process.env, BACKEND_PORT: String(backendPort) };
delete backendEnv.PORT;

runNpmScript("dev", frontendEnv);
runNpmScript("dev:backend", backendEnv);

for (const sig of ["SIGINT", "SIGTERM", "SIGHUP"]) {
  process.on(sig, () => {
    shuttingDown = true;
    for (const child of children) {
      if (!child.killed) {
        child.kill(sig);
      }
    }
  });
}
